version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: miniio-media-master-api
    ports:
      - "49000:9000"   # MinIO API
      - "49001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: kokoro-tts-service
    environment:
      - DOWNLOAD_MODEL=true
    ports:
      - "8880:8880" 
    restart: unless-stopped

  api:
    build: .
    container_name: media-master-api
    ports:
      - "48000:8000"
    environment:
      - API_KEY=${API_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - KOKORO_TIMEOUT=120
      - KOKORO_MAX_TEXT_LENGTH=1000
    depends_on:
      - minio
      - kokoro-tts
    restart: unless-stopped

volumes:
  minio_data:

networks:
  default:
    driver: bridge
        